// <auto-generated />
using System;
using ExpFastEnpoints.ExpFastEndpoints.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpFastEnpoints.Migrations.PatumbaCentralDatabaseMigrations
{
    [DbContext(typeof(PatumbaCentralDatabase))]
    [Migration("20250617100755_investmenthousenewfieldsnew")]
    partial class investmenthousenewfieldsnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:Enum:public.inactivity_band", "seven_days,fourteen_days,thirty_days,thirty_one_to_sixty_days,sixty_one_to_ninety_days,ninety_one_to_one_twenty_days,one_twenty_one_to_one_eighty_days,one_eighty_one_to_three_sixty_five_days")
                .HasAnnotation("Npgsql:Enum:public.order_type", "sell,buy")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.FixedTermDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("InterestAmount")
                        .HasColumnType("double");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double");

                    b.Property<int>("InvestmentHouseId")
                        .HasColumnType("int");

                    b.Property<double>("MaturityAmount")
                        .HasColumnType("double");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentHouseId");

                    b.ToTable("fixed_term_deposits", "public");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("CertificateOfIncorporation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryOfIncorporation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfIncorporation")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Financials")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("TaxClearanceCertificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tpin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("TradingLicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("investment_houses", "public");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.FixedTermDeposit", b =>
                {
                    b.HasOne("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", "InvestmentHouse")
                        .WithMany("FixedTermDeposits")
                        .HasForeignKey("InvestmentHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentHouse");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+ContactPerson", "ContactPersons", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("ContactPerson", "public");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+Director", "Directors", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("Director", "public");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.Navigation("ContactPersons");

                    b.Navigation("Directors");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.Navigation("FixedTermDeposits");
                });
#pragma warning restore 612, 618
        }
    }
}
