// <auto-generated />
using System;
using ExpFastEnpoints.ExpFastEndpoints.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpFastEnpoints.Migrations.PatumbaCentralDatabaseMigrations
{
    [DbContext(typeof(PatumbaCentralDatabase))]
    [Migration("20250617100023_investmenthousenewfields")]
    partial class investmenthousenewfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:Enum:public.inactivity_band", "seven_days,fourteen_days,thirty_days,thirty_one_to_sixty_days,sixty_one_to_ninety_days,ninety_one_to_one_twenty_days,one_twenty_one_to_one_eighty_days,one_eighty_one_to_three_sixty_five_days")
                .HasAnnotation("Npgsql:Enum:public.order_type", "sell,buy")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("CertificateOfIncorporation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryOfIncorporation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfIncorporation")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Financials")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InstitutionType")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TaxClearanceCertificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Tpin")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TradingLicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("investment_houses", "public");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+ContactPerson", "ContactPersons", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("ContactPerson", "public");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+Director", "Directors", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("Director", "public");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.Navigation("ContactPersons");

                    b.Navigation("Directors");
                });
#pragma warning restore 612, 618
        }
    }
}
