// <auto-generated />
using System;
using ExpFastEnpoints.ExpFastEndpoints.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpFastEnpoints.Migrations.PatumbaCentralDatabaseMigrations
{
    [DbContext(typeof(PatumbaCentralDatabase))]
    [Migration("20250619093305_FixedTermInvestmentHouseEquity")]
    partial class FixedTermInvestmentHouseEquity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.Equity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<double>("SharePrice")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.FixedTermDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("InterestAmount")
                        .HasColumnType("double");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double");

                    b.Property<int>("InvestmentHouseId")
                        .HasColumnType("int");

                    b.Property<double>("MaturityAmount")
                        .HasColumnType("double");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentHouseId");

                    b.ToTable("fixed_term_deposits", (string)null);
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<bool?>("CertificateOfIncorporation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryOfIncorporation")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateOfIncorporation")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Financials")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InstitutionType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TaxClearanceCertificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Tpin")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TradingLicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("investment_houses", (string)null);
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.FixedTermDeposit", b =>
                {
                    b.HasOne("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", "InvestmentHouse")
                        .WithMany("FixedTermDeposits")
                        .HasForeignKey("InvestmentHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentHouse");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+ContactPerson", "ContactPersons", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("ContactPerson");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.OwnsMany("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse+Director", "Directors", b1 =>
                        {
                            b1.Property<int>("InvestmentHouseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Position")
                                .HasColumnType("longtext");

                            b1.HasKey("InvestmentHouseId", "Id");

                            b1.ToTable("Director");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentHouseId");
                        });

                    b.Navigation("ContactPersons");

                    b.Navigation("Directors");
                });

            modelBuilder.Entity("ExpFastEnpoints.ExpFastEndpoints.Core.Models.InvestmentHouse", b =>
                {
                    b.Navigation("FixedTermDeposits");
                });
#pragma warning restore 612, 618
        }
    }
}
